name: jaybuys
favicon: null
layout_spectrum: 0.7453909781761467
typography_spectrum: 0.3861023709177971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4643715664278716
  lightness: 0.7104461884591728
  saturation: 0.2520483585540205
  rhythmicContrast: 0.5609946185722947
purpose: []
